from __future__ import annotations

from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape

TEMPLATES_DIR = Path(__file__).parent / "templates"

BASIC_TASK_PY = '''"""Basic test suite - generated by autoplat scaffold."""
from robocorp import browser
from robocorp.tasks import task, setup, teardown


@setup
def suite_setup(task):
    """Configure browser before tests."""
    browser.configure(
        browser_engine="chromium",
        headless=True,
        screenshot="only-on-failure",
    )


@teardown
def suite_teardown(task):
    """Cleanup after tests."""
    browser.close()


@task
def test_page_loads():
    """Verify the main page loads successfully. Tags: smoke, P0"""
    browser.goto("https://example.com")
    page = browser.page()
    title = page.title()
    assert title, "Page should have a title"
    print(f"Page title: {title}")


@task
def test_heading_exists():
    """Verify the main heading is present. Tags: smoke, P1"""
    browser.goto("https://example.com")
    page = browser.page()
    heading = page.locator("h1")
    assert heading.count() > 0, "Expected at least one h1 heading"
    print(f"Heading text: {heading.first.text_content()}")
'''

BASIC_PYPROJECT = '''[project]
name = "my-test-project"
version = "0.1.0"
description = "UI automation test project"
requires-python = ">=3.10"
dependencies = [
    "robocorp-tasks>=4.0.0",
    "robocorp-browser>=2.3.4",
    "ui-autoplat",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
'''

BASIC_AUTOPLAT_YAML = '''# autoplat.yaml - Test platform configuration
browser:
  type: chromium
  headless: true
  screenshot: only-on-failure
  viewport:
    width: 1280
    height: 720

execution:
  mode: subprocess
  retries: 0
  timeout_per_test: 300

output:
  dir: ./output
  # html, json, junit, allure, or all
  report_format: html

discovery:
  paths:
    - ./tests
  file_pattern: "*task*.py"

profiles:
  dev:
    browser:
      headless: false
      slowmo: 100
      screenshot: on
  ci:
    browser:
      headless: true
      record_video: true
    execution:
      max_parallel: 4
      retries: 2
'''

BASIC_README = '''# {project_name}

UI automation test project generated by **autoplat**.

## Quick Start

```bash
# Install dependencies
pip install -e .

# Run all tests (headless)
autoplat run

# Run with visible browser
autoplat run --headed

# Run smoke tests only
autoplat run --tags smoke

# List discovered tests
autoplat discover

# Run in dev mode (visible, slow)
autoplat run --profile dev
```

## Project Structure

```
tests/              # Test task files
  basic_task.py     # Basic page load tests
autoplat.yaml       # Platform configuration
pyproject.toml      # Python project metadata
```

## Writing Tests

Create files matching `*task*.py` in the `tests/` directory:

```python
from robocorp import browser
from robocorp.tasks import task

@task
def test_something():
    \"\"\"Description. Tags: smoke, P1\"\"\"
    browser.goto("https://example.com")
    page = browser.page()
    # Your test logic here
```
'''


class ScaffoldGenerator:
    def generate(
        self,
        project_name: str,
        template: str = "basic",
        output_dir: Path | None = None,
    ) -> None:
        output_dir = output_dir or Path.cwd()
        project_dir = output_dir / project_name

        if project_dir.exists():
            raise FileExistsError(f"Directory already exists: {project_dir}")

        project_dir.mkdir()
        tests_dir = project_dir / "tests"
        tests_dir.mkdir()
        (project_dir / "output" / "reports").mkdir(parents=True)
        (project_dir / "output" / "screenshots").mkdir(parents=True)

        if template == "basic":
            self._generate_basic(project_dir, project_name, tests_dir)
        else:
            self._generate_basic(project_dir, project_name, tests_dir)
            click_echo(f"Note: Template '{template}' uses basic template as base.")

    def init_current_dir(self, template: str = "basic") -> None:
        cwd = Path.cwd()
        config_file = cwd / "autoplat.yaml"
        if config_file.exists():
            raise FileExistsError(f"autoplat.yaml already exists in {cwd}")

        tests_dir = cwd / "tests"
        tests_dir.mkdir(exist_ok=True)
        (cwd / "output" / "reports").mkdir(parents=True, exist_ok=True)
        (cwd / "output" / "screenshots").mkdir(parents=True, exist_ok=True)

        config_file.write_text(BASIC_AUTOPLAT_YAML, encoding="utf-8")

        task_file = tests_dir / "example_task.py"
        if not task_file.exists():
            task_file.write_text(BASIC_TASK_PY, encoding="utf-8")

    def _generate_basic(self, project_dir: Path, project_name: str, tests_dir: Path) -> None:
        (project_dir / "pyproject.toml").write_text(
            BASIC_PYPROJECT.format(project_name=project_name), encoding="utf-8"
        )
        (project_dir / "autoplat.yaml").write_text(BASIC_AUTOPLAT_YAML, encoding="utf-8")
        (project_dir / "README.md").write_text(
            BASIC_README.format(project_name=project_name), encoding="utf-8"
        )
        (tests_dir / "basic_task.py").write_text(BASIC_TASK_PY, encoding="utf-8")


def click_echo(msg: str) -> None:
    print(msg)
